### ISSUE TITLE
Ways to control output

### ISSUE THREAD

**Issue by suntong** [spakin/awk#3]
Any plan to implement the [awk-inplace-modification](http://stackoverflow.com/questions/16529716/awk-save-modifications-inplace) feature, in near or far future? 

I need such a feature now, so I guess I have to scratch my own itch. However I took a look at [awk godoc](https://godoc.org/github.com/spakin/awk#Script.Run), but didn't find a way to control its output. 

Comments? Thx.

**Comment by spakin** [comment]
I wasn't planning on it.  It should be easy enough, though, for you to initialize the [`Script`](https://godoc.org/github.com/spakin/awk#Script)'s `Output` field to a temporary file (say, with [`ioutil.TempFile`](https://golang.org/pkg/io/ioutil/#TempFile)) then [`os.Rename`](https://golang.org/pkg/os/#Rename) it back to the original file name at the end of the script, no?

A problem with trying to automate this feature is that the Go package doesn't know the name of the original file.  In fact, because a [`Script`](https://godoc.org/github.com/spakin/awk#Script) takes an [`io.Writer`](https://golang.org/pkg/io/#Writer) to write to, it may not even _be_ a file.

— Scott

**Comment by suntong** [comment]
Ok. Thanks for describing how to do it ourselves.

**Comment by suntong** [comment]
FTA, I found that the best way to deal with this inplace-modification situation is to use awk with the pipe package. Ref https://github.com/suntong/lang/blob/master/lang/Go/src/sys/Pipe_Awk.go for a working sample how they can work together.
